### ISSUE TITLE
PlayerEx with Sinytra Connector crashes with Origins

### ISSUE THREAD

**Issue by Raiiiden** [PlayerEXDirectorsCut/playerex#22]
https://mclo.gs/pbZiJtn

**Comment by cassie-jfs** [comment]
Will be resolved in alpha 14 (this is due to an outdated, JIJ version of AdditionalEntityAttributes from forge: origins that is out of sync with the upstream AdditionalEntityAttributes). A failsafe to obtaining id's for attributes will be done to prevent this, and warnings will be displayed for specific attributes which can not be located.
