### ISSUE TITLE
PlayerEx on Sinytra Connector crashes when generating new world, and data error when loading an old world

### ISSUE THREAD

**Issue by ToppyTopology** [PlayerEXDirectorsCut/playerex#28]
First thank you for making it load into sinytra, one of the best stats mod. 

Im using forge 47.3.0, and latest version of all mods. Its mostly likely an issue with the data attributes mod

[crash-2024-08-09_17.54.31-client.txt](https://github.com/user-attachments/files/16559778/crash-2024-08-09_17.54.31-client.txt)

**Comment by cassie-jfs** [comment]
Hi.
If you want something that works with Sinytra Connector, we have a rewrite available on the latest PlayerEX on the alpha channel that is relatively stable.

This would be https://modrinth.com/mod/playerex-directors-cut/version/4.0.0+1.20.1-alpha.13 joined with the latest beta version of data attributes.

As for 3.7.3+1.20.1, it uses the old system and is not stable with Connector due to dynamically registering attributes past the usual stage.
